# **Lesson 02: Introduction to NumPy**

This notebook introduces the fundamentals of NumPy, Python's powerful numerical computing library.  
We'll cover array creation, basic operations, broadcasting, indexing, and more.

📌 **Plan**:  

- 🔢 Creating arrays  
- 🧩 Multi-dimensional arrays  
- 🎲 Randomly generated arrays  
- ⚡ Element-wise operations  
  - 🔍 Comparison operations  
  - ✅ Logical operations  
- 📊 Summarizing operations  



## **🔹 Importing NumPy**
We start by importing **NumPy** with the alias `np`, which is the standard convention used in almost all projects.  
This makes it easier and faster to call NumPy functions.

📖 Official documentation: [NumPy Reference](https://numpy.org/doc/)

## **📚 Interesting Background**

NumPy (short for **Numerical Python**) was originally created in 2005 by **Travis Oliphant**, who merged two earlier Python libraries: **Numeric** and **Numarray**.  
It quickly became the **core scientific computing library in Python**, forming the foundation of libraries such as **pandas, SciPy, scikit-learn, TensorFlow, and PyTorch**.

🔗 Learn more about the history and impact of NumPy:

- [The History of NumPy (Nature article)](https://www.nature.com/articles/d41586-020-03382-2)  
- [NumPy: The fundamental package for scientific computing in Python (Official About page)](https://numpy.org/about/)



In [1]:
import numpy as np

## **🔹 Creating Arrays**

NumPy arrays are the core data structure used for numerical computations.  
They are more efficient and flexible than Python lists, allowing fast operations on large datasets.

We can create arrays in multiple ways:
- From Python lists or tuples  
- Using built-in functions like `np.zeros()`, `np.ones()`, `np.arange()`, and `np.linspace()`  
- With random number generators such as `np.random.rand()`  

👉 Arrays form the foundation for all operations in NumPy.


In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [10]:
a[2]

np.int64(3)

In [11]:
a[2] = 10

In [12]:
a

array([ 1,  2, 10,  5,  7, 12])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
np.linspace(0,100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## **🔹 Multi-dimensional Arrays**

NumPy supports arrays with more than one dimension (also called **matrices** or **tensors**).  
These allow us to represent data in rows and columns, or even higher dimensions.

Common examples:
- 2D arrays → tables or matrices  
- 3D arrays → images or stacked data  
- nD arrays → tensors for advanced computations (e.g., in deep learning)

👉 Multi-dimensional arrays are the foundation of numerical computing, enabling operations on structured data.


In [19]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
n = np.array([[1,2,3],
         [4,5,6],
         [7,8,9]
         ])

In [23]:
n[0][2]

np.int64(3)

In [24]:
n[0,1] = 10

In [26]:
n[0]

array([ 1, 10,  3])

In [27]:
n[2] = [1,1,1]

In [28]:
n

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [29]:
n[:,1]

array([10,  5,  1])

In [30]:
n[:, 2]

array([3, 6, 1])

In [31]:
n[:, 2] = [0,1,2]

In [32]:
n

array([[ 1, 10,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## **🔹 Randomly Generated Arrays**

NumPy provides tools for generating arrays filled with random numbers.  
These arrays are useful for simulations, testing algorithms, or initializing model parameters.  

You can generate:
- Uniformly distributed numbers with `np.random.rand()`  
- Normally distributed numbers with `np.random.randn()`  
- Random integers with `np.random.randint()`  

👉 Random arrays are essential when working with probabilistic models, machine learning, and data sampling.


In [36]:
np.random.rand(5,2)

array([[0.79725456, 0.96690625],
       [0.99727305, 0.2875957 ],
       [0.48708916, 0.32630265],
       [0.03657006, 0.43549415],
       [0.40311678, 0.15724101]])

In [37]:
np.random.seed(10)

## **🔹 Element-wise Operations**

NumPy allows mathematical operations to be applied **element by element** across arrays.  
This makes computations fast and concise compared to traditional Python loops.  

Examples include:
- Arithmetic operations: `+`, `-`, `*`, `/`, `**`  
- Comparison operations: `<`, `>`, `==`, `!=`  
- Logical operations: `&`, `|`, `~`  

👉 Element-wise operations are one of the key reasons NumPy is so powerful for numerical computing.


In [40]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [41]:
a + 1

array([1, 2, 3, 4, 5])

In [42]:
b = (10 + (a * 2)) ** 2 / 100

In [43]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [44]:
a / b

array([0.        , 0.69444444, 1.02040816, 1.171875  , 1.2345679 ])

In [45]:
a / b +10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

### **🔹 Comparison Operations**

NumPy supports element-wise comparison between arrays or between an array and a scalar.  
The result is a boolean array indicating whether the condition is `True` or `False`.  

Examples:
- `a > 5` → checks if each element is greater than 5  
- `a == 0` → checks equality with zero  

👉 Useful for filtering, masking, and conditional operations on data.


In [46]:
a 

array([0, 1, 2, 3, 4])

In [47]:
a >= 2

array([False, False,  True,  True,  True])

In [48]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [49]:
a > b

array([False, False,  True,  True,  True])

In [50]:
a[a>b]

array([2, 3, 4])

### **🔹 Logical Operations**

Logical operations combine multiple boolean conditions element-wise.  
They return arrays of `True`/`False` values based on logical rules.  

Examples:
- `&` → logical AND  
- `|` → logical OR  
- `~` → logical NOT  

👉 Logical operations are often used with comparisons to build complex conditions, e.g. `(a > 2) & (a < 10)`.


## **🔹 Summarizing Operations**

NumPy provides functions to quickly compute summary statistics across arrays.  
These operations can be applied to the entire array or along specific axes (rows or columns).  

Common examples:
- `np.sum()` → total of all elements  
- `np.mean()` → average value  
- `np.min()`, `np.max()` → minimum and maximum values  
- `np.std()` → standard deviation  

👉 Summarizing operations are essential for understanding the overall properties of your data.


In [51]:
a

array([0, 1, 2, 3, 4])

In [53]:
a.max()

np.int64(4)